onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - less
  - lmdb
  - mongodb-memory-server
  - msgpackr-extract
  - nx
  - puppeteer
  - unrs-resolver
