import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';                   
import { catchError, map, tap } from 'rxjs/operators';
import { environment } from '../../../environments/environment';
import { LoggerService } from './logger.service';

export interface HistoricalPoint {
  date: Date;
  close: number;
}
export interface HistoricalData {
  symbol: string;
  data: HistoricalPoint[];
}
type HistoricalApiPoint = { timestamp?: number[]; close?: number[] };
type HistoricalApiResponse = Record<string, HistoricalApiPoint>;

@Injectable({
  providedIn: 'root',
})
export class YahooService {
  // use the path configured in environment.yahooFinance.url; if
  // additional apiUrl prefix exists we prepend it.  This matches the
  // values generated by generate-env.js and avoids hard‑coding the
  // "financial" segment that caused 404s.
  private apiUrl = `${environment.apiUrl}${environment.yahooFinance?.url || '/api/yahoo'}`;

  constructor(
    private http: HttpClient,
    private logger: LoggerService,
  ) {
    this.logger.registerService('YahooService');
    this.logger.info('YahooService initialized');
  }

  getStockQuote(symbol: string): Observable<Record<string, unknown>> {
    const url = `${this.apiUrl}/quote/${symbol}`;

    this.logger.debug(`Fetching stock quote for ${symbol}`, { url });
    const callId = this.logger.startServiceCall('YahooService', 'GET', url);

    return this.http.get<Record<string, unknown>>(url).pipe(
      tap(() => this.logger.endServiceCall(callId, 200)),
      catchError(error => {
        this.logger.error(`Error fetching stock quote for ${symbol}:`, {
          status: error.status,
          statusText: error.statusText,
          message: error.message,
        });
        this.logger.endServiceCall(callId, error.status || 500);
        return of({});                                
      }),
    );
  }

  getHistoricalData(symbols: string[], interval: string = '1d', range: string = '1y', limit: number = 1000): Observable<HistoricalData[]> {
    const url = `${this.apiUrl}/historical`;
    const params = { interval, range, symbols: symbols.join(','), limit: `${limit}` };

    this.logger.debug(`Fetching historical data for ${symbols}`, { url });
    const callId = this.logger.startServiceCall('YahooService', 'GET', url);

    return this.http.get<HistoricalApiResponse>(url, { params }).pipe(
      map(response => {
        this.logger.endServiceCall(callId, 200);
        const responseMap = new Map(Object.entries(response || {}));
        const parsedData: HistoricalData[] = symbols.map(symbol => {
          // Sanitize symbol to avoid untrusted object property access and potential injection
          const safeSymbol = String(symbol || '').trim();
          if (!/^[A-Za-z0-9.\-]+$/.test(safeSymbol)) {
            return { symbol, data: [] };
          }
          // Accessing response object by dynamic key is controlled (symbol sanitized above)
          // eslint-disable-next-line security/detect-object-injection
          const data = responseMap.get(safeSymbol) as HistoricalApiPoint | undefined;
          if (!data?.timestamp?.length || !data?.close?.length) {
            return {
              symbol,
              data: [],
            };
          }
          // eslint-disable-next-line security/detect-object-injection
          return {
            symbol,
            data: data.timestamp.map((timestamp: number, index: number) => ({
              date: new Date(timestamp * 1000),
              // eslint-disable-next-line security/detect-object-injection
              close: data.close?.[index] ?? 0,
            })),
          };
        });
        return parsedData;
      }),
      catchError(error => {
        this.logger.error(`Error fetching historical data for ${symbols}:`, {
          status: error.status,
          statusText: error.statusText,
          message: error.message,
        });
        this.logger.endServiceCall(callId, error.status || 500);
        return of([] as HistoricalData[]);                                       
      }),
    );
  }

  getMarketSummary(): Observable<Record<string, unknown>[]> {
    const url = `${this.apiUrl}/market-summary`;

    this.logger.debug(`Fetching market summary`, { url });
    const callId = this.logger.startServiceCall('YahooService', 'GET', url);

    return this.http.get<Record<string, unknown>[]>(url).pipe(
      tap(() => this.logger.endServiceCall(callId, 200)),
      catchError(error => {
        this.logger.error(`Error fetching market summary:`, {
          status: error.status,
          statusText: error.statusText,
          message: error.message,
        });
        this.logger.endServiceCall(callId, error.status || 500);
        return of([]);                                       
      }),
    );
  }

  getTrendingSymbols(region: string): Observable<Record<string, unknown>[]> {
    const url = `${this.apiUrl}/trending`;
    const params = { region };

    this.logger.debug(`Fetching trending symbols for region ${region}`, { url });
    const callId = this.logger.startServiceCall('YahooService', 'GET', url);

    return this.http.get<Record<string, unknown>[]>(url, { params }).pipe(
      tap(() => this.logger.endServiceCall(callId, 200)),
      catchError(error => {
        this.logger.error(`Error fetching trending symbols for region ${region}:`, {
          status: error.status,
          statusText: error.statusText,
          message: error.message,
        });
        this.logger.endServiceCall(callId, error.status || 500);
        return of([]);                                       
      }),
    );
  }

  getCompanyDetails(symbol: string): Observable<Record<string, unknown> | null> {
    const url = `${this.apiUrl}/company/${symbol}`;

    this.logger.debug(`Fetching company details for ${symbol}`, { url });
    const callId = this.logger.startServiceCall('YahooService', 'GET', url);

    return this.http.get<Record<string, unknown>>(url).pipe(
      tap(() => this.logger.endServiceCall(callId, 200)),
      catchError(error => {
        this.logger.error(`Error fetching company details for ${symbol}:`, {
          status: error.status,
          statusText: error.statusText,
          message: error.message,
        });
        this.logger.endServiceCall(callId, error.status || 500);
        return of(null);                                
      }),
    );
  }
}
