// This file was generated by generate-env.js
export const environment = {
  production: true,
  apiUrl: 'https://jeffreysanford.us',
  host: 'jeffreysanford.us',
  finnHubAPI: 'https://finnhub.io/api/v1',
  nasaFirms: {
    endpoint: 'https://firms.modaps.eosdis.nasa.gov/api/active-fires',
  },
  calFire: {
    endpoint: 'https://www.fire.ca.gov/api',
  },
  flightRadar24: {
    apiKey: '',
    endpoint: 'https://fr24api.flightradar24.com/api/sandbox',
  },
  yahooFinance: {
    url: '/api/yahoo',
  },
  socket: {
    url: 'wss://jeffreysanford.us'
  }
};
