// This file was generated by generate-env.js
export const environment = {
  production: false,
  apiUrl: '', // Empty string for local development (proxy)
  logLevel: 'debug',
  useOfflineMode: false,
  enableDebug: true,
  useApiMocks: false,
  sentryDsn: '',
  version: '0.1.0',
  healthCheckEndpoint: '/health',
  maxRetryAttempts: 3,
  retryDelayMs: 1000,
  alphaVantageApiKey: 'demo',
  yahooFinance: {
    url: '/api/yahoo',
    apiKey: 'demo_key'
  },
  flightRadar24: {
    endpoint: '/api/flight-radar',
    apiKey: 'demo_key'
  },
  mapbox: {
    accessToken: 'pk.demo.mapbox_token'
  },
  OPENSKY_USERNAME: 'demo',
  OPENSKY_PASSWORD: 'demo',
  socket: {
    url: 'http://localhost:3000'
  }
};
