const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load .env file
const envConfig = dotenv.config({ path: path.join(__dirname, '..', '..', '.env') }).parsed || {};

const targetPath = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');
const targetDevPath = path.join(__dirname, 'src', 'environments', 'environment.ts');

const envConfigFile = `// This file was generated by generate-env.js
export const environment = {
  production: true,
  apiUrl: '${process.env.API_URL || envConfig.API_URL || 'https://jeffreysanford.us'}',
  host: '${process.env.HOST_NAME || envConfig.HOST_NAME || 'jeffreysanford.us'}',
  finnhubApiKey: '${process.env.FINNHUB_API_KEY || envConfig.FINNHUB_API_KEY || ''}',
  finnHubAPI: 'https://finnhub.io/api/v1',
  mapbox: {
    accessToken: '${process.env.MAPBOX_ACCESS_TOKEN || envConfig.MAPBOX_ACCESS_TOKEN || ''}',
  },
  nasaFirms: {
    apiKey: '${process.env.NASA_FIRMS_API_KEY || envConfig.NASA_FIRMS_API_KEY || ''}',
    endpoint: 'https://firms.modaps.eosdis.nasa.gov/api/active-fires',
  },
  calFire: {
    endpoint: 'https://www.fire.ca.gov/api',
  },
  flightRadar24: {
    apiKey: '${process.env.FLIGHTRADAR24_API_KEY || envConfig.FLIGHTRADAR24_API_KEY || ''}',
    endpoint: 'https://fr24api.flightradar24.com/api/sandbox',
  },
  alphaVantageApiKey: '${process.env.ALPHA_VANTAGE_API_KEY || envConfig.ALPHA_VANTAGE_API_KEY || ''}',
  yahooFinance: {
    url: '/api/yahoo',
    apiKey: '${process.env.YAHOO_FINANCE_API_KEY || envConfig.YAHOO_FINANCE_API_KEY || ''}'
  },
  socket: {
    url: '${process.env.SOCKET_URL || envConfig.SOCKET_URL || 'wss://jeffreysanford.us'}'
  }
};
`;

const envConfigDevFile = `// This file was generated by generate-env.js
export const environment = {
  production: false,
  apiUrl: '', // Empty string for local development (proxy)
  logLevel: 'debug',
  useOfflineMode: false,
  enableDebug: true,
  useApiMocks: false,
  sentryDsn: '',
  version: '0.1.0',
  healthCheckEndpoint: '/health',
  maxRetryAttempts: 3,
  retryDelayMs: 1000,
  alphaVantageApiKey: '${process.env.ALPHA_VANTAGE_API_KEY || envConfig.ALPHA_VANTAGE_API_KEY || 'demo'}',
  yahooFinance: {
    url: '/api/yahoo',
    apiKey: '${process.env.YAHOO_FINANCE_API_KEY || envConfig.YAHOO_FINANCE_API_KEY || ''}'
  },
  socket: {
    url: 'http://localhost:3000'
  }
};
`;

fs.writeFileSync(targetPath, envConfigFile);
fs.writeFileSync(targetDevPath, envConfigDevFile);
console.log('Successfully generated environment files.');
