package main

import (
	"craft-fusion/craft-go/handlers"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "craft-fusion/craft-go/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Craft Fusion API
// @version 1.0
// @description This is a sample server for Craft Fusion.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:4000
// @BasePath /
func main() {
	router := gin.Default()

	// Set trusted proxies
	// router.SetTrustedProxies([]string{"127.0.0.1"})

	// Enable CORS from localhost:4200 and jeffreysanford.us
	router.Use(func(c *gin.Context) {
		origin := c.Request.Header.Get("Origin")
		if origin == "http://localhost:4200" || origin == "https://jeffreysanford.us" {
			c.Writer.Header().Set("Access-Control-Allow-Origin", origin)
		}
		c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})

	// Enable Gzip Compression
	router.Use(gzip.Gzip(gzip.DefaultCompression))

	// Health Check
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "OK"})
	})

	// User Records API
	router.GET("/records", handlers.GetRecordsHandler)
	router.GET("/records/generate", handlers.GenerateRecordsHandler)
	router.GET("/records/time", handlers.GetCreationTimeHandler) // Ensure the correct route
	router.GET("/records/:UID", handlers.GetRecordByUIDHandler)  // Ensure the correct route

	// Swagger
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Log all registered routes
	for _, route := range router.Routes() {
		fullURL := fmt.Sprintf("http://localhost:4000%s", route.Path)
		log.Printf("Endpoint: %s %s", route.Method, fullURL)
	}

	log.Println("Starting Go Backend on :4000")

	srv := &http.Server{
		Addr:         ":4000",
		Handler:      router,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  30 * time.Second,
	}

	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("listen: %s\n", err)
	}
}
