package main

import (
	"craft-fusion/craft-go/handlers"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "craft-fusion/craft-go/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Craft Fusion API
// @version 1.0
// @description This is a sample server for Craft Fusion.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:4000
// @BasePath /
func main() {
	router := gin.Default()

	// Middleware: CORS
	router.Use(func(c *gin.Context) {
		allowedOrigins := map[string]bool{
			"http://localhost:4200":     true,
			"https://jeffreysanford.us": true,
		}
		origin := c.Request.Header.Get("Origin")
		if allowedOrigins[origin] {
			c.Writer.Header().Set("Access-Control-Allow-Origin", origin)
		} else {
			log.Printf("CORS: Unauthorized origin %s", origin)
		}
		c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")
		c.Writer.Header().Set("Access-Control-Max-Age", "86400") // Cache preflight response for 24 hours

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})

	// Middleware: Gzip Compression
	router.Use(gzip.Gzip(gzip.DefaultCompression))

	// Health Check and API Status
	router.GET("/api-go/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "OK"})
	})
	router.GET("/api-go/api/status", handlers.GetApiStatusHandler)
	router.GET("/health", func(c *gin.Context) { // Add direct health endpoint
		c.JSON(200, gin.H{"status": "OK"})
	})

	// Metrics API - expanded paths for better compatibility
	router.GET("/api-go/metrics", handlers.GetMetricsHandler)
	router.GET("/api-go/api/metrics", handlers.GetMetricsHandler)
	router.GET("/metrics", handlers.GetMetricsHandler)
	router.GET("/api-go/v1/metrics", handlers.GetMetricsHandler)
	router.GET("/api-go/metrics/go", handlers.GetMetricsHandler)

	// Add more path variations to ensure compatibility
	router.GET("/api/metrics", handlers.GetMetricsHandler)
	router.GET("/api/metrics/go", handlers.GetMetricsHandler)

	// Handle root path to provide basic information
	router.GET("/", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"service": "Go API Server",
			"status":  "running",
			"endpoints": []string{
				"/metrics",
				"/api-go/metrics",
				"/api/metrics",
				"/health",
			},
		})
	})

	// OAuth Routes
	router.GET("/api-go/oauth/nest/authorize", handlers.NestAuthorizeHandler)
	router.GET("/api-go/oauth/nest/callback", handlers.NestCallbackHandler)
	router.POST("/api-go/oauth/nest/token", handlers.NestTokenHandler)
	router.POST("/api-go/oauth/nest/refresh", handlers.NestRefreshHandler)
	router.POST("/api-go/oauth/nest/revoke", handlers.NestRevokeHandler)

	// User Records API
	router.GET("/api-go/records", handlers.GetRecordsHandler)
	router.GET("/api-go/records/generate", handlers.GenerateRecordsHandler)
	router.GET("/api-go/records/time", handlers.GetCreationTimeHandler)
	router.GET("/api-go/records/:UID", handlers.GetRecordByUIDHandler)

	// Swagger
	router.GET("/api-go/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Log all registered routes
	for _, route := range router.Routes() {
		fullURL := fmt.Sprintf("http://localhost:4000%s", route.Path)
		log.Printf("Endpoint: %s %s", route.Method, fullURL)
	}

	log.Println("Starting Go Backend on :4000")

	// Server Configuration
	srv := &http.Server{
		Addr:         ":4000",
		Handler:      router,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  30 * time.Second,
	}

	// Start the Server
	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("listen: %s\n", err)
	}
}
